### ISSUE TITLE
Failing to create the ./db/changes directory.

### ISSUE THREAD

**Issue by brinlyau** [jruesga/cm-cloud-generator#2]
Error log: 

2015-09-29 03:58:05 INFO CloudGenerator - Collecting data
Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:292)
at CloudGenerator.fetchAllGerritCommits(CloudGenerator.java:371)
at CloudGenerator.main(CloudGenerator.java:106)

**Comment by brinlyau** [comment]
Patch up
